### ISSUE TITLE
Missing header/Installaton error

### ISSUE THREAD

**Issue by kaysahu** [yutingsdu/Tiglon-v.1.1#1]
Hi,

I was attempting to run Tiglon. I successfully installed BAMTOOLS and Boost by following the procedure mentioned in the Tiglon README. Tiglon build was completed successfully and I have the 5 files in the src/bin/ folder.

![image](https://github.com/yutingsdu/Tiglon-v.1.1/assets/53317454/fcea4f7f-399d-4591-a020-4dc3b09b7932)

However, during runtime, tiglon gives me this error:

![image](https://github.com/yutingsdu/Tiglon-v.1.1/assets/53317454/d9a57cf9-6984-4688-9294-c572ad3ebf0f)

This same issue also occurs during the testing of the ./run_me.sh script. Can you please advise regarding the same?

**Comment by yutingsdu** [comment]
It seems that you didn't set the LD_LIBRARY_PATH environment variable.

**Comment by yutingsdu** [comment]
Please you: export LD_LIBRARY_PATH=/home/yuting/local/boost/lib:$LD_LIBRARY_PATH

**Comment by kaysahu** [comment]
Hello. Sorry I should have mentioned this in my previous comment.

In my script I export the library path.
export LD_LIBRARY_PATH=/work/yaolab/shared/2023_05_Consemble/boost_1_82_0/lib:$LD_LIBRARY_PATH
pkg_path=/work/yaolab/shared/2023_05_Consemble/tiglon_new_attempt/Tiglon-v.1.1/
Tiglon_outdir=/work/yaolab/shared/2023_05_Consemble/Tiglon-v.1.1/friday_result_SUNDAY_test
bamFiles_list=/work/yaolab/shared/2023_05_Consemble/Tiglon-v.1.1/bamfile.txt
$pkg_path/Tiglon -B $bamFiles_list -s first -o $Tiglon_outdir -p 16


Can you please tell me if this what we want to use as command line argument?

**Comment by yutingsdu** [comment]
As far as I can tell, it is right, however, I am not sure if _absolute path_ works for -o option.

**Comment by kaysahu** [comment]
Hello,

I tried my script using a relative path for example: './outputfolder'. However, the error message seems to be the same. Do you have any suggestions regarding this?

![image](https://github.com/yutingsdu/Tiglon-v.1.1/assets/53317454/866d4874-3b75-483c-9ca7-d9a9f2a68e23)

**Comment by yutingsdu** [comment]
For now, I am so sorry that I am not sure what is the problem. Would you please try another version of boost, such as boost_1_60_0? This version was used for designing Tiglon.

**Comment by kaysahu** [comment]
Thank you for the update. Boost_1_60_0 worked and I was able to execute Tiglon successfully.
However, the run time of 96 hours was not enough. I only have one folder and two files, which were last updated when I submitted my script. 
![image](https://github.com/yutingsdu/Tiglon-v.1.1/assets/53317454/87da2323-cdfc-41ac-bd36-d7259c57158a)

This is the command line I am using:
$pkg_path/Tiglon -B $bamFiles_list -s first -o $Tiglon_outdir -p 4

Can you suggest any other parameter to make this go faster?  I am using a single BAM file for testing which is only 260M in size.

**Comment by yutingsdu** [comment]
The running command you used was right, I am not sure why Tiglon was running so slowly. We are sorry for this, and StringTie can be a good alternative.

**Comment by kaysahu** [comment]
Thank you for the update. I will try your suggestion.
